app/urls.py
from django.urls import path
# from app.views import hello, job_detail
from app import views

#from . import views 
#. means current folder

urlpatterns = [  
    path('', views.job_list, name='jobs_home'),
    path('hello/', views.hello, name='hello'),
    # path('job/1', views.job_detail),
    path('job/<int:id>', views.job_detail, name='job_detail'),
    # path('job/<str:id>', views.job_detail),
    # path('job_list', views.job_list, name)
]

job/urls.py
from django.contrib import admin
# from django.http import HttpResponse
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


#move to views.py in app
# def hello(request):
#     return HttpResponse("Hello World")

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app.urls')),
    # path('', hello),  #delete it and move to urls.py in app
    #but add path directing to app.urls
    path('', include('subscribe.urls')),
    path('uploads/', include('uploadapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #\
  #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#the static things help to show image after its get verified or saved
#add MEDIA_URL/ROOT in job settings.py

subscribe/urls.py
from django.urls import path
from . import views


#move to views.py in app
# def hello(request):
#     return HttpResponse("Hello World")

urlpatterns = [
    path('subscribe/', views.subscribe, name='subscribe'),
     path('thank_you/', views.thank_you, name='thank_you')
   
]

subscribe/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
NEWSLETTER_OPTION = [
    ('W', 'Weekly'),
    ('M', 'Monthly')
]

class Subscribe(models.Model):
    first_name=models.CharField(max_length=100, help_text="Enter characters only")
    last_name=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)
    option = models.CharField(max_length=2, choices=NEWSLETTER_OPTION)
    # option = models.CharField(max_length=2, choices=NEWSLETTER_OPTION, default='M')


# def save(self, *args, **kwargs):
#         if not self.id:

#             self.slug = slugify(self.title)
#         #eturn self.save(*args, **kwargs)
#         return super(Subscribe, self).save(*args, **kwargs)

subscribe/forms.py
from django import forms
from subscribe.models import Subscribe
from django.utils.translation import gettext_lazy as _

#modern form
class SubscribeForm(forms.ModelForm):
    class Meta:
        model=Subscribe
        fields='__all__'
        #exclude=('first_name')
        labels={
            'first_name':_('Enter first name'),
            'last_name':_('Enter last name'),
            'email':_('Enter email')

        }
        # help_texts={
        #     'first_name':_("Enter characters only")
        # },  #use forms.as_p  in html
        error_messages={
            'first_name':{
                'required':_('first name is required'),
            },
        }
# def validate_comma(value):
#         if ',' in value:
#             raise forms.ValidationError("Invalid last name")
#         return value
# class SubscribeForm(forms.Form):
#     first_name=forms.CharField(max_length=100, validators=[validate_comma], label="Enter first name")
#     last_name=forms.CharField(max_length=100, disabled=False, validators=[validate_comma], label="Enter last name")
#     email=forms.EmailField(max_length=100, required=False, label="Enter email", help_text="Enter characters only")

#     # def clean_first_name(self):
    #     data = self.cleaned_data['first_name']
    #     if ',' in data:
    #         raise forms.ValidationError("Invalid first name")
    #     return data

subscribe/views.py
from django.shortcuts import render, redirect
from subscribe.forms import SubscribeForm
from subscribe.models import Subscribe
from django.urls import reverse


# Create your views here.
def subscribe(request):
    subscribe_form = SubscribeForm()
    email_error_empty=''
    print('1')
    if request.POST:
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
           #in response to modern form
           subscribe_form.save()
           return redirect(reverse('thank_you'))




            # print('valid form')
            # print(subscribe_form.cleaned_data)
            # email = subscribe_form.cleaned_data['email']
            # # first_name = subscribe_form.clean_first_name
            # first_name = subscribe_form.cleaned_data['first_name']
            # last_name = subscribe_form.cleaned_data['last_name']
            # print(email)
            # subscribe = Subscribe(first_name=first_name, last_name=last_name, email=email)
            # subscribe.save()
            # return redirect(reverse('thank_you'))
    # if request.POST:
    #     #first_name here is from javascript
    #     first_name = request.POST['firstname']
    #     last_name = request.POST['lastname']
    #     email = request.POST['email']
    #     print("post", email)
    #     if email=="":
    #         email_error_empty="No email entered"
    #     subscribe = Subscribe(first_name=first_name, last_name=last_name, email=email)
    #     subscribe.save()
    context = {"form": subscribe_form, "email_error_empty": email_error_empty}
    return render(request, 'subscribe/subscribe.html', context)
def thank_you(request):
    context={}
    return render(request, 'subscribe/thank_you.html', context)

subscribe/templates/subscribe/subscribe.html
{% extends 'base.html' %}
{% block title %} FlixCareers | Subscribe {% endblock%}

{% block content %}
<section>
  <div class="container">
      <form class="email-form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <!-- <p>
          <label for="id_first_name">Enter First Name:</label>
          <input type="text" name="first_name" maxlength="100" required id="id_first_name">
        </p>
        <p>
          <label for="id_last_name">Enter Last Name:</label>
          <input type="text" name="last_name" maxlength="100" required id="id_last_name">
        </p>
        <p>
          <label for="id_email">Enter Email:</label>
          <input type="email" name="email" maxlength="100" required id="id_email"> 
        </p>
        <p>
          <label for="id_option">Option:</label>
          <select name="option" id="id_option">
        <option value="W">Weekly</option>
        <option value="M" selected>Monthly</option>
      </select>
        </p> -->
      <button class="email-submit">Submit</button>
      </form>
</div>
  </div>
</section>
{% endblock content %}



<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
    <title>Subscribe Form</title>
  
</head> -->
<!-- <body>
    <h1><img src="{% static 'subscribe/balmuda.png' %}" alt="subscribe">Subscribe Form</h1>
      <form method="post">
        {% csrf_token %} 
        {{form.as_p}} -->
        <!-- {{ form.as_table }} -->

        <!-- {{ form }}
        <input type="submit" value="Submit"> -->

        
        <!-- {% if email_error_empty %}
        <p>{{ email_error_empty }}</p>
        {% endif %}-->


        <!-- {% for field in form %}
        <div class="subscribe_field">
            {{field.errors}}
            <label for="{{field.id_for_label}}">{{field.label}}</label>
           
            {{field}}
        </div>
        {% endfor %} -->
         <!-- {{field.label_tag}} -->
        


        <!-- <div class="subscribe_field">
       {{ form.first_name.errors }}
        <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}}</label>
        {{ form.first_name }} -->
        <!-- <input type="text" id="f_name" name="firstname" placeholder="Your First Name" required> -->
        <!-- <br>
        </div>
        <div class="subscribe_field">
        {{ form.last_name.errors }}
        <label for="{{form.last_name.id_for_label}}">{{form.last_name.label}}</label>
        {{ form.last_name }} -->
        <!-- <label for="l_name">Last Name</label>
        <input type="text" id="l_name" name="lastname" placeholder="Your Last Name" required> -->
        <!-- <br>
        </div>
        <div class="subscribe_field">
        {{ form.email.errors }}
        <label for="{{form.email.id_for_label}}">{{form.email.label}}</label>
        {{ form.email }} -->
        <!-- <label for="email">Email</label>
        <input type="email" id="email" name="email" placeholder="Your Email" required> -->
        <!-- <br>
        </div> -->
        <!-- <input type="submit" value="Submit"> 
 
      </form>
      <button onclick="popup()">Click me</button>
      <script src="{% static 'subscribe/main.js' %}">
       
      </script>
    
</body>
</html> -->

subscribe/templates/subscribe/thank_you.html
{% extends 'base.html' %}
{% block title %} FlixCareers | Thank you {% endblock%}

{% block content %}
<section>
    <div class="container">
        <p>Thank you for your submission</p>
    </div>
</section>

    
{% endblock content %}